In [1]:
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train', shuffle=True, random_state=42)

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape


(11314, 130107)

In [3]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer().fit(X_train_counts)
X_train = tf_transformer.transform(X_train_counts)
X_train

<11314x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [31]:
X_train.shape

(11314, 130107)

In [17]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
# fix random seed for reproducibility
numpy.random.seed(7)

In [5]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=130107, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [6]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [10]:
X_train.todense()

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [14]:
X_train = X_train.todense()

In [26]:
X_train[0].shape

(1, 130107)

In [29]:
np.where(X_train[0][0] > 0)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([  4605,  16574,  18299,  26073,  27436,  28615,  32311,  34181,
         34995,  35187,  35612,  35983,  37433,  37565,  37780,  40998,
         42876,  45295,  48618,  48620,  50111,  50527,  51730,  51793,
         56979,  56989,  57308,  62221,  63363,  64095,  65798,  66098,
         66608,  67156,  68532,  68766,  73201,  74693,  75358,  76032,
         76718,  76722,  78784,  78955,  79666,  80638,  83256,  85354,
         86001,  86580,  87620,  89362,  89860,  90252,  90379,  90686,
         90774,  92081,  94362,  95162,  96144,  98949,  99822, 101378,
        104813, 106116, 108252, 109271, 109581, 111322, 113986, 114428,
        114455, 114579, 114688, 114731, 115475, 118

In [12]:
model.fit(X_train, twenty_train.target)

Epoch 1/10
 4928/11314 [============>.................] - ETA: 14s - loss: -17.9609 - acc: 0.0522

KeyboardInterrupt: 